# Generated by Django 3.0.5 on 2020-06-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_name', models.CharField(max_length=150)),
                ('teach_surname', models.CharField(max_length=150)),
                ('teach_email', models.EmailField(max_length=254)),
                ('teach_number', models.CharField(max_length=200)),
                ('teach_files', models.FileField(upload_to='teach_files')),
                ('teach_message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=100)),
                ('from_surname', models.CharField(max_length=150)),
                ('from_email', models.EmailField(max_length=250)),
                ('phone_number', models.CharField(max_length=100)),
                ('sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
