# Generated by Django 3.0.5 on 2020-06-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='teach_surname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='from_surname',
        ),
    ]
