# Generated by Django 3.0.6 on 2020-05-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200522_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='email',
            new_name='from_email',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='username',
            new_name='from_user',
        ),
    ]
