# Generated by Django 3.0.5 on 2020-06-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200608_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='topic',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
