# Generated by Django 3.0.6 on 2020-05-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('teach_email', models.EmailField(max_length=254)),
                ('teach_number', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=150)),
                ('teach_mail', models.FileField(upload_to='teach_files')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
