# Generated by Django 3.0.6 on 2020-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_career'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='teach_mail',
            new_name='teach_files',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='name',
            new_name='teach_name',
        ),
        migrations.RemoveField(
            model_name='career',
            name='sector',
        ),
        migrations.AddField(
            model_name='career',
            name='teach_message',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
