# Generated by Django 3.0.5 on 2020-06-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200526_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='teach_surname',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='surname',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='from_surname',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
    ]
