# Generated by Django 3.0.5 on 2020-06-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200608_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='topic',
        ),
    ]
